#!/usr/bin/env bash
# This script use awk && bash function to print info on subdomains

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
    record=$(dig +short "$sub.$domain" | awk '{ print $1 }')
    type=$(dig +short "$sub.$domain" | awk '{ print $4 }')
    echo "The subdomain $sub is a $type record and points to $record"
done
