#!/usr/bin/env bash
# Install and configure nginx so that its HTTP response contains a custom header (on web-01 and web-02)

sudo apt-get  update
sudo apt-get -y install nginx

# Open Nginx configuration file for editing
sudo sed -i '/http {/a add_header X-Served-By $hostname;' /etc/nginx/nginx.conf

# Restart the nginx service to apply the changes
sudo service nginx restart
