#!/usr/bin/env bash
# This script installs and configure HAproxy on lb-01 server so that it send traffic to web-01 and web-02.

sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAproxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo touch /etc/haproxy/haproxy.cfg

echo "global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 52.90.13.53-web-01:80 check
    server web-02 52.91.131.227-web-02:80 check
    timeout connect 5s
    timeout server 30s
    timeout check 5s" | sudo tee /etc/haproxy/haproxy.cfg

# Enable HAproxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAproxy
sudo service haproxy restart
