#!/usr/bin/env bash
# This script installs and configure HAproxy on lb-01 server so that it send traffic to web-01 and web-02.

sudo apt-get update
sudo apt-get install -y haproxy 
echo '
frontend http-in
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 111478-web-01 52.91.183.27:80
        server 111478-web-02 35.174.211.32:80
' >> /etc/haproxy/haproxy.cfg

# Enable HAproxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAproxy
sudo service haproxy restart
