#!/usr/bin/env bash
# This script setup nginx to listen to port 80
sudo service nginx status 

# Check if Nginx is listening on port 80
sudo netstat -tuln | grep 80

# Check if there are any errors in the Nginx configuration file
sudo nginx -t

# Check if there are any other processes running on port 80
sudo lsof -i :80

# Configure Nginx to listen on port 80 of all the server's active IPv4 IPs
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx
sudo service nginx restart
